project:
  type: website
  output-dir: _site

website:
  title: "myblog"
  page-navigation: true
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Notes
        href: notes/index.qmd
      - text: About
        href: about.qmd
    right:
      - icon: twitter
        aria-label: X
        href: https://x.com/eclectical93914
        target: _blank
      - icon: github
        aria-label: GitHub
        href: https://github.com/eclectically
        target: _blank

format:
  html:
    theme: cosmo

execute:
  freeze: auto
  cache: true
  echo: true
  warning: false
  message: false
  kernel: myblog
